# torchtitan Config.toml

[job]
dump_folder = "./outputs"
description = "Llama 3 debug training"
# TODO: turn this back on once ci have tokenizer
use_for_integration_test = true

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 10

[metrics]
log_freq = 1
enable_color_printing = true
enable_tensorboard = true
save_tb_folder = "tb"

[model]
name = "llama3"
flavor = "5B"
norm_type = "fused_rmsnorm"  # layernorm / np_layernorm / rmsnorm / fused_rmsnorm
# test tokenizer.model, for debug purpose only
tokenizer_path = "./test/assets/test_tiktoken.model"

[optimizer]
name = "FAdam" # [ AdamW, FAdam ]
lr = 8e-4
beta1 = 0.9
beta2 = 0.999
weight_decay = 0.01

[training]
batch_size = 8
seq_len = 2048
warmup_steps = 400  # lr scheduler warm up, normally 20% of the train steps
max_norm = 10.0  # grad norm clipping
steps = 1000
data_parallel_degree = -1
tensor_parallel_degree = 1
fp8_linear = ""
compile = false
dataset = "c4"  # supported datasets: c4_mini (45K), c4 (177M)

[experimental]
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = false
folder = "checkpoint"
interval_type = "steps"
interval = 500
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'none'  # ['none', 'selective', 'full']
selective_ac_option = '2'  # 'int' = ac every positive int layer or 'op', ac based on ops policy
